language: php

git:
  depth: 5

matrix:
  include:
    - php: 5.5
      dist: precise
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4snapshot

install:
  - composer self-update
  - composer install

script:
  - vendor/bin/phug-dev check --report --coverage-php-version=5.6

notifications:
  slack: phug:nzXFnxhU14RWK2EQSDL0u08z

addons:
  code_climate:
    repo_token: 602a8a0b82958fea9a62c990e1e73446096cacef7d194e46de0a94144b1d66f2
